const TABLE_SESSION_TTL_SECONDS =
  Number(process.env.TABLE_SESSION_TTL_SECONDS) || 30 * 60;
const TABLE_SESSION_HEARTBEAT_TTL_SECONDS =
  Number(process.env.TABLE_SESSION_HEARTBEAT_TTL_SECONDS) ||
  TABLE_SESSION_TTL_SECONDS;

const TABLE_SESSION_LOCK_TTL_MS =
  Number(process.env.TABLE_SESSION_LOCK_TTL_MS) || 3000;
const TABLE_SESSION_LOCK_WAIT_MS =
  Number(process.env.TABLE_SESSION_LOCK_WAIT_MS) || 50;
const TABLE_SESSION_LOCK_RETRIES =
  Number(process.env.TABLE_SESSION_LOCK_RETRIES) || 3;

module.exports = {
  TABLE_SESSION_TTL_SECONDS,
  TABLE_SESSION_HEARTBEAT_TTL_SECONDS,
  TABLE_SESSION_LOCK_TTL_MS,
  TABLE_SESSION_LOCK_WAIT_MS,
  TABLE_SESSION_LOCK_RETRIES,
};
